<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>SysWeaver.FileTranslation</RootNamespace>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <NoWarn>1701;1702;1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="HtmlAgilityPack" Version="1.12.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\SwSolidity\Solidity.Common\Solidity.Common.csproj" />
  </ItemGroup>

</Project>
