<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <RootNamespace>SysWeaver.HttpTransformer</RootNamespace>
    <NoWarn>1701;1702;1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Magick.NET-Q16-x64" Version="14.12.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SysWeaver.HttpServer\SysWeaver.HttpServer.csproj" />
  </ItemGroup>

</Project>
