using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace SysWeaver.Net
{

    /// <summary>
    /// A simple immutable implementation of <see cref="IHttpServerEndPoint"/>, used by modules to describe the end points (files, folders, APIs) they serve.
    /// </summary>
    public class HttpServerEndPoint : IHttpServerEndPoint
    {

        /// <summary>
        /// The local url of the end point.
        /// </summary>
        public readonly String Uri;
        /// <summary>
        /// The type of end point.
        /// </summary>
        public readonly HttpServerEndpointTypes Type;
        /// <summary>
        /// The http method(s) the end point responds to, may be null.
        /// </summary>
        public readonly String Method;
        /// <summary>
        /// The mime type of the response, null for folders.
        /// </summary>
        public readonly String Mime;
        /// <summary>
        /// Number of seconds the client may cache the response.
        /// </summary>
        public readonly int ClientCacheDuration;
        /// <summary>
        /// Number of seconds the response is cached on the server.
        /// </summary>
        public readonly int RequestCacheDuration;
        /// <summary>
        /// Not used (always false).
        /// </summary>
        public readonly bool UseStream;
        /// <summary>
        /// The compression preference, ex: "br:Fast, deflate:Fast", null if not compressed.
        /// </summary>
        public readonly String Compression;
        /// <summary>
        /// The http code of the encoding that the source data is pre-compressed with (ex: "br"), null if not pre-compressed.
        /// </summary>
        public readonly String Decoder;
        /// <summary>
        /// Tokens required to access the end point (any of them), null if no auth is required.
        /// </summary>
        public readonly IReadOnlyList<String> Auth;
        /// <summary>
        /// A description of where the data comes from (ex: a disc path or "Generated by ...").
        /// </summary>
        public readonly String Location;
        /// <summary>
        /// The size of the data in bytes, if known.
        /// </summary>
        public readonly long? Size;
        /// <summary>
        /// When the data was last modified (defaults to the application start time).
        /// </summary>
        public readonly DateTime LastModified;
        /// <summary>
        /// Optional custom (lower cased) properties, null for folders.
        /// </summary>
        public readonly IReadOnlySet<String> Props;

        /// <summary>
        /// Constructor for files (and other data end points).
        /// </summary>
        /// <param name="uri">The local url</param>
        /// <param name="method">The http method(s)</param>
        /// <param name="clientCacheDuration">Number of seconds the client may cache the response</param>
        /// <param name="requestCacheDuration">Number of seconds the response is cached on the server</param>
        /// <param name="compression">The compression preference, null if not compressed</param>
        /// <param name="decoder">The http code of the pre-compression encoding, null if not pre-compressed</param>
        /// <param name="auth">Tokens required to access the end point, null if no auth is required</param>
        /// <param name="type">The type of end point</param>
        /// <param name="location">A description of where the data comes from</param>
        /// <param name="size">The size in bytes, if known</param>
        /// <param name="lastModified">When the data was last modified, null for the application start time</param>
        /// <param name="etag">The etag of the data</param>
        /// <param name="mime">The mime type of the response</param>
        /// <param name="props">A custom hash set of properties (use only lowercase), frozen by the constructor</param>
        public HttpServerEndPoint(string uri, string method, int clientCacheDuration, int requestCacheDuration, string compression, string decoder, IReadOnlyList<String> auth, HttpServerEndpointTypes type, String location, long? size, DateTime? lastModified, String etag, String mime, IReadOnlySet<String> props)
        {
            Uri = uri;
            Type = type;
            Method = method;
            ClientCacheDuration = clientCacheDuration;
            RequestCacheDuration = requestCacheDuration;
            Compression = compression;
            Decoder = decoder;
            Auth = auth;
            Location = location;
            Size = size;
            LastModified = lastModified ?? HttpServerTools.StartedTime;
            ETag = etag;
            Mime = mime;
            Props = props.Freeze();
        }

        /// <summary>
        /// Constructor for folders.
        /// </summary>
        /// <param name="uri">The local url of the folder</param>
        /// <param name="location">A description of where the data comes from</param>
        /// <param name="lastModified">When the folder was last modified, null for the application start time</param>
        /// <param name="etag">The etag of the folder</param>
        /// <param name="type">The type of end point</param>
        /// <param name="method">The http method(s), may be null</param>
        public HttpServerEndPoint(string uri, String location, DateTime? lastModified, String etag, HttpServerEndpointTypes type = HttpServerEndpointTypes.Folder, String method = null)
        {
            Uri = uri;
            Location = location;
            LastModified = lastModified ?? HttpServerTools.StartedTime;
            ETag = etag;
            Type = type;
            Method = method;
        }


        /// <summary>
        /// The etag of the data, may be null.
        /// </summary>
        public readonly String ETag;
        /// <inheritdoc/>
        public override string ToString() => String.Concat('"', Uri, "\" @ ", Location);


        string IHaveUri.Uri => Uri;

        HttpServerEndpointTypes IHttpServerEndPoint.Type => Type;

        string IHttpServerEndPoint.Method => Method;

        int IHttpServerEndPoint.ClientCacheDuration => ClientCacheDuration;

        int IHttpServerEndPoint.RequestCacheDuration => RequestCacheDuration;

        string IHttpServerEndPoint.CompPreference => Compression;

        string IHttpServerEndPoint.PreCompressed => Decoder;
        IReadOnlyList<String> IHttpServerEndPoint.Auth => Auth;
        string IHttpServerEndPoint.Location=> Location;
        long? IHttpServerEndPoint.Size => Size;

        DateTime IHttpServerEndPoint.LastModified => LastModified;
        String IHttpServerEndPoint.ETag => ETag;

        string IHttpServerEndPoint.Mime => Mime;

    }
}
