<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0-windows</TargetFramework>
		<GenerateDocumentationFile>True</GenerateDocumentationFile>
		<RootNamespace>SysWeaver.WebBrowser</RootNamespace>
		<NoWarn>1701;1702;1591</NoWarn>
		<CefSharpBuildAction>Content</CefSharpBuildAction>
		<CefSharpAnyCpuSupport>true</CefSharpAnyCpuSupport>
	</PropertyGroup>

	<ItemGroup>
	  <PackageReference Include="CefSharp.OffScreen.NETCore" Version="150.0.110" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\SysWeaver.Common\SysWeaver.Common.csproj" />
		<ProjectReference Include="..\SysWeaver.MicroService.MySqlAudit\SysWeaver.MicroService.MySqlAudit.csproj" />
		<ProjectReference Include="..\SysWeaver.WebBrowser\SysWeaver.WebBrowser.csproj" />
	</ItemGroup>
</Project>
