<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <TargetFramework>net10.0</TargetFramework>
	  <GenerateDocumentationFile>True</GenerateDocumentationFile>
	  <RootNamespace>SysWeaver.MicroService</RootNamespace>
	  <NoWarn>1701;1702;1591</NoWarn>
  </PropertyGroup>

	<Target Name="EmbedLocal" BeforeTargets="BeforeBuild">
		<Exec Command="..\_tools\compress\Compress.exe -Methods br .\srcWeb\*+ .\web" />
		<ItemGroup>
			<EmbeddedResource Include="web\**\*.br" Visible="false" />
		</ItemGroup>
	</Target>

	<ItemGroup>
	  <ProjectReference Include="..\SysWeaver.Common\SysWeaver.Common.csproj" />
	  <ProjectReference Include="..\SysWeaver.Compression\SysWeaver.Compression.csproj" />
	  <ProjectReference Include="..\SysWeaver.MicroServices.ServiceManager\SysWeaver.MicroServices.ServiceManager.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="srcWeb\mediaView\imageEffects\" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="Magick.NET-Q16-x64" Version="14.10.3" />
	</ItemGroup>
</Project>
