using System;
using System.Collections.Generic;

namespace SysWeaver.Media
{

    public enum MediaTypes
    {
        None = 0,
        Image,
        Video,
        Audio,
    }


    public static class MediaFileTypes
    {

        /// <summary>
        /// Get the type of media for a given file extension
        /// </summary>
        /// <param name="fileExtension">The file extension</param>
        /// <returns>The media type</returns>
        public static MediaTypes GetMediaType(String fileExtension)
        {
            if (String.IsNullOrEmpty(fileExtension))
                return MediaTypes.None;
            return FileTypes.TryGetValue(fileExtension.TrimStart('.').FastToLower(), out var x) ? x : MediaTypes.None;
        }

        static readonly IReadOnlyDictionary<String, MediaTypes> FileTypes = new Dictionary<string, MediaTypes>(StringComparer.Ordinal)
        {
            { "apng", MediaTypes.Image },
            { "art", MediaTypes.Image },
            { "arw", MediaTypes.Image },
            { "avci", MediaTypes.Image },
            { "avcs", MediaTypes.Image },
            { "avif", MediaTypes.Image },
            { "avifs", MediaTypes.Image },
            { "bmp", MediaTypes.Image },
            { "bpg", MediaTypes.Image },
            { "brf", MediaTypes.Image },
            { "cal", MediaTypes.Image },
            { "cals", MediaTypes.Image },
            { "cin", MediaTypes.Image },
            { "cmx", MediaTypes.Image },
            { "cod", MediaTypes.Image },
            { "cr2", MediaTypes.Image },
            { "crw", MediaTypes.Image },
            { "cube", MediaTypes.Image },
            { "cur", MediaTypes.Image },
            { "cut", MediaTypes.Image },
            { "dcm", MediaTypes.Image },
            { "dcr", MediaTypes.Image },
            { "dcx", MediaTypes.Image },
            { "dds", MediaTypes.Image },
            { "dib", MediaTypes.Image },
            { "dicom", MediaTypes.Image },
            { "djvu", MediaTypes.Image },
            { "dng", MediaTypes.Image },
            { "dot", MediaTypes.Image },
            { "dpx", MediaTypes.Image },
            { "emf", MediaTypes.Image },
            { "eps", MediaTypes.Image },
            { "exr", MediaTypes.Image },
            { "fax", MediaTypes.Image },
            { "ff", MediaTypes.Image },
            { "fits", MediaTypes.Image },
            { "flif", MediaTypes.Image },
            { "fpx", MediaTypes.Image },
            { "gif", MediaTypes.Image },
            { "heic", MediaTypes.Image },
            { "heics", MediaTypes.Image },
            { "heif", MediaTypes.Image },
            { "heifs", MediaTypes.Image },
            { "hpgl", MediaTypes.Image },
            { "hrz", MediaTypes.Image },
            { "ico", MediaTypes.Image },
            { "ief", MediaTypes.Image },
            { "j2c", MediaTypes.Image },
            { "j2k", MediaTypes.Image },
            { "jbig", MediaTypes.Image },
            { "jfif", MediaTypes.Image },
            { "jng", MediaTypes.Image },
            { "jp2", MediaTypes.Image },
            { "jpc", MediaTypes.Image },
            { "jpe", MediaTypes.Image },
            { "jpeg", MediaTypes.Image },
            { "jpg", MediaTypes.Image },
            { "jxl", MediaTypes.Image },
            { "jxr", MediaTypes.Image },
            { "mac", MediaTypes.Image },
            { "mat", MediaTypes.Image },
            { "miff", MediaTypes.Image },
            { "mng", MediaTypes.Image },
            { "mpo", MediaTypes.Image },
            { "msl", MediaTypes.Image },
            { "mvg", MediaTypes.Image },
            { "nef", MediaTypes.Image },
            { "ora", MediaTypes.Image },
            { "orf", MediaTypes.Image },
            { "otb", MediaTypes.Image },
            { "palm", MediaTypes.Image },
            { "pam", MediaTypes.Image },
            { "pbm", MediaTypes.Image },
            { "pcd", MediaTypes.Image },
            { "pcl", MediaTypes.Image },
            { "pct", MediaTypes.Image },
            { "pcx", MediaTypes.Image },
            { "pdb", MediaTypes.Image },
            { "pef", MediaTypes.Image },
            { "pes", MediaTypes.Image },
            { "pfa", MediaTypes.Image },
            { "pfb", MediaTypes.Image },
            { "pgm", MediaTypes.Image },
            { "pic", MediaTypes.Image },
            { "pict", MediaTypes.Image },
            { "pix", MediaTypes.Image },
            { "png", MediaTypes.Image },
            { "pnm", MediaTypes.Image },
            { "pnt", MediaTypes.Image },
            { "pntg", MediaTypes.Image },
            { "pnz", MediaTypes.Image },
            { "ppm", MediaTypes.Image },
            { "psb", MediaTypes.Image },
            { "psd", MediaTypes.Image },
            { "pwp", MediaTypes.Image },
            { "qoi", MediaTypes.Image },
            { "qti", MediaTypes.Image },
            { "qtif", MediaTypes.Image },
            { "raf", MediaTypes.Image },
            { "ras", MediaTypes.Image },
            { "rf", MediaTypes.Image },
            { "rgb", MediaTypes.Image },
            { "rgba", MediaTypes.Image },
            { "rgf", MediaTypes.Image },
            { "rle", MediaTypes.Image },
            { "sct", MediaTypes.Image },
            { "sfw", MediaTypes.Image },
            { "sgi", MediaTypes.Image },
            { "sid", MediaTypes.Image },
            { "sun", MediaTypes.Image },
            { "svg", MediaTypes.Image },
            { "tga", MediaTypes.Image },
            { "tif", MediaTypes.Image },
            { "tiff", MediaTypes.Image },
            { "tim", MediaTypes.Image },
            { "ttf", MediaTypes.Image },
            { "vicar", MediaTypes.Image },
            { "viff", MediaTypes.Image },
            { "wbmp", MediaTypes.Image },
            { "wdp", MediaTypes.Image },
            { "webp", MediaTypes.Image },
            { "wmf", MediaTypes.Image },
            { "wpg", MediaTypes.Image },
            { "x3f", MediaTypes.Image },
            { "xbm", MediaTypes.Image },
            { "xcf", MediaTypes.Image },
            { "xpm", MediaTypes.Image },
            { "xwd", MediaTypes.Image },
            { "yuv", MediaTypes.Image },
            { "3g2", MediaTypes.Video },
            { "3gp", MediaTypes.Video },
            { "3gp2", MediaTypes.Video },
            { "3gpp", MediaTypes.Video },
            { "asf", MediaTypes.Video },
            { "asr", MediaTypes.Video },
            { "asx", MediaTypes.Video },
            { "avi", MediaTypes.Video },
            { "axv", MediaTypes.Video },
            { "cpk", MediaTypes.Video },
            { "dif", MediaTypes.Video },
            { "divx", MediaTypes.Video },
            { "dv", MediaTypes.Video },
            { "f4v", MediaTypes.Video },
            { "flv", MediaTypes.Video },
            { "gxf", MediaTypes.Video },
            { "IVF", MediaTypes.Video },
            { "lsf", MediaTypes.Video },
            { "lsx", MediaTypes.Video },
            { "m1v", MediaTypes.Video },
            { "m2t", MediaTypes.Video },
            { "m2ts", MediaTypes.Video },
            { "m2v", MediaTypes.Video },
            { "m4v", MediaTypes.Video },
            { "mk3d", MediaTypes.Video },
            { "mkv", MediaTypes.Video },
            { "mod", MediaTypes.Video },
            { "mov", MediaTypes.Video },
            { "movie", MediaTypes.Video },
            { "mp2", MediaTypes.Video },
            { "mp2v", MediaTypes.Video },
            { "mp4", MediaTypes.Video },
            { "mp4v", MediaTypes.Video },
            { "mpa", MediaTypes.Video },
            { "mpd", MediaTypes.Video },
            { "mpe", MediaTypes.Video },
            { "mpeg", MediaTypes.Video },
            { "mpg", MediaTypes.Video },
            { "mpv2", MediaTypes.Video },
            { "mqv", MediaTypes.Video },
            { "mts", MediaTypes.Video },
            { "mxf", MediaTypes.Video },
            { "nsc", MediaTypes.Video },
            { "nut", MediaTypes.Video },
            { "ogv", MediaTypes.Video },
            { "qt", MediaTypes.Video },
            { "rm", MediaTypes.Video },
            { "roq", MediaTypes.Video },
            { "swf", MediaTypes.Video },
            { "ts", MediaTypes.Video },
            { "tts", MediaTypes.Video },
            { "vbk", MediaTypes.Video },
            { "webm", MediaTypes.Video },
            { "wm", MediaTypes.Video },
            { "wmp", MediaTypes.Video },
            { "wmv", MediaTypes.Video },
            { "wmx", MediaTypes.Video },
            { "wtv", MediaTypes.Video },
            { "wvx", MediaTypes.Video },
            { "302", MediaTypes.Audio },
            { "aa", MediaTypes.Audio },
            { "AAC", MediaTypes.Audio },
            { "aax", MediaTypes.Audio },
            { "ac3", MediaTypes.Audio },
            { "ADT", MediaTypes.Audio },
            { "ADTS", MediaTypes.Audio },
            { "adx", MediaTypes.Audio },
            { "afc", MediaTypes.Audio },
            { "aif", MediaTypes.Audio },
            { "aifc", MediaTypes.Audio },
            { "aiff", MediaTypes.Audio },
            { "al", MediaTypes.Audio },
            { "amr", MediaTypes.Audio },
            { "apm", MediaTypes.Audio },
            { "aptx", MediaTypes.Audio },
            { "aptxhd", MediaTypes.Audio },
            { "ast", MediaTypes.Audio },
            { "au", MediaTypes.Audio },
            { "axa", MediaTypes.Audio },
            { "bit", MediaTypes.Audio },
            { "c2", MediaTypes.Audio },
            { "caf", MediaTypes.Audio },
            { "cdda", MediaTypes.Audio },
            { "dts", MediaTypes.Audio },
            { "eac3", MediaTypes.Audio },
            { "flac", MediaTypes.Audio },
            { "g722", MediaTypes.Audio },
            { "gsm", MediaTypes.Audio },
            { "ircam", MediaTypes.Audio },
            { "lbc", MediaTypes.Audio },
            { "m3u", MediaTypes.Audio },
            { "m3u8", MediaTypes.Audio },
            { "m4a", MediaTypes.Audio },
            { "m4b", MediaTypes.Audio },
            { "m4p", MediaTypes.Audio },
            { "m4r", MediaTypes.Audio },
            { "mid", MediaTypes.Audio },
            { "midi", MediaTypes.Audio },
            { "mka", MediaTypes.Audio },
            { "mlp", MediaTypes.Audio },
            { "mmf", MediaTypes.Audio },
            { "mp3", MediaTypes.Audio },
            { "msbc", MediaTypes.Audio },
            { "oga", MediaTypes.Audio },
            { "ogg", MediaTypes.Audio },
            { "oma", MediaTypes.Audio },
            { "opus", MediaTypes.Audio },
            { "pcm", MediaTypes.Audio },
            { "pls", MediaTypes.Audio },
            { "ra", MediaTypes.Audio },
            { "ram", MediaTypes.Audio },
            { "rco", MediaTypes.Audio },
            { "rmi", MediaTypes.Audio },
            { "rpm", MediaTypes.Audio },
            { "rso", MediaTypes.Audio },
            { "sb", MediaTypes.Audio },
            { "sbc", MediaTypes.Audio },
            { "sd2", MediaTypes.Audio },
            { "sf", MediaTypes.Audio },
            { "smd", MediaTypes.Audio },
            { "smx", MediaTypes.Audio },
            { "smz", MediaTypes.Audio },
            { "snd", MediaTypes.Audio },
            { "sox", MediaTypes.Audio },
            { "spdif", MediaTypes.Audio },
            { "spx", MediaTypes.Audio },
            { "sw", MediaTypes.Audio },
            { "tco", MediaTypes.Audio },
            { "thd", MediaTypes.Audio },
            { "tta", MediaTypes.Audio },
            { "tun", MediaTypes.Audio },
            { "ub", MediaTypes.Audio },
            { "ul", MediaTypes.Audio },
            { "uw", MediaTypes.Audio },
            { "vag", MediaTypes.Audio },
            { "voc", MediaTypes.Audio },
            { "w64", MediaTypes.Audio },
            { "wav", MediaTypes.Audio },
            { "wave", MediaTypes.Audio },
            { "wax", MediaTypes.Audio },
            { "wma", MediaTypes.Audio },
            { "wv", MediaTypes.Audio },
        }.Freeze();

    }
}
