<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<RootNamespace>SysWeaver.Media</RootNamespace>
		<GenerateDocumentationFile>True</GenerateDocumentationFile>
		<NoWarn>1701;1702;1591</NoWarn>
		<AllowUnsafeBlocks>True</AllowUnsafeBlocks>
	</PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Magick.NET-Q16-x64" Version="14.16.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SysWeaver.CommandLine\SysWeaver.CommandLine.csproj" />
    <ProjectReference Include="..\SysWeaver.Storage\SysWeaver.Storage.csproj" />
  </ItemGroup>

</Project>
